---
- hosts: managedvm
  become: true
  tasks:
    - name: Get OS type
      shell: uname -s
      register: OS_TYPE

    - name: Get Archi...
      shell: uname -m
      register: ARC_TYPE

    - name: uptdate cache
      apt:
        update_cache: yes
    
    - name: Install python pip
      apt:
        name: pip 
        state: present

    - name: Install docker python package
      pip:
        name: docker

    - name: Download docker script
      get_url:
        url : "https://get.docker.com"
        dest:  /home/vagrant/get-docker.sh
        mode: 'u+x,g+x'
    
    - name: Install docker
      command: /home/vagrant/get-docker.sh
      register: myoutput

    - name: Echo output
      debug:
        msg: '{{ myoutput.stdout_lines}}'
    
    - name: Add vagrant user to the docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes

    - name: Install docker-compose from official github repo
      get_url:
        url : "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ OS_TYPE.stdout }}-{{ ARC_TYPE.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/ttsz/ColorConverterApp.git'
        dest: /home/vagrant/colorconvert

    - name: Build an image
      docker_image:
        path: /home/vagrant/colorconvert
        name: colorconverter
        tag: version-2.0

    - name: Create a data container
      docker_container:
        name: colorconverter
        image: colorconverter:version-2.0
        env: PORT=3000
        published_ports:
          - 3000:3000
