- name: Create custom directory
  file:
    state: directory
    path: '{{ path }}'

- name: Create custom file
  copy:
    dest: '{{ path }}/hello-{{ item }}.txt'
    content: 'Welcome {{ item }} '
  loop: ["alma", "korte", "barack"]