- name: Test file handling in a custom directory
  vars:
    path: '{{ ansible_env.HOME }}/flow/testfolder'
  block:

    - name: Include create-file.yml
      include: create-file.yml

    - name: Include debug.yml
      include: debug.yml

